modLoader="javafml"
loaderVersion="${target_loader}"
issueTrackerURL="https://github.com/IMB11/Fog/issues"
displayURL="http://IMB11.dev/"
logoFile="assets/fog/icon.png"
authors="IMB11,Steveplays"
license="All-Rights-Reserved"

[[mods]]
modId="fog"
version="${mod_version}"
displayName="Fog"
description="An expansive and dynamic overhaul to Minecraft's fog rendering system."

[[dependencies.fog]]
modId="${loader}"
${mandatory_inclusion_field}
versionRange="${target_loader}"
ordering="NONE"
side="BOTH"

[[dependencies.fog]]
modId="minecraft"
${mandatory_inclusion_field}
versionRange="${target_minecraft}"
ordering="NONE"
side="BOTH"

[[dependencies.fog]]
modId = "yet_another_config_lib_v3"
${mandatory_inclusion_field}
versionRange = "[3.5.0,)"

[[dependencies.fog]]
modId="mru"
${mandatory_inclusion_field}
versionRange="${target_mru}"
ordering="NONE"
side="BOTH"

[[mixins]]
config="fog.mixins.json"
